export const cities = [
  "Bruxelles",
  "Jette",
  "Molenbeek-Saint-Jean",
  "Koekelberg",
  "Uccle",
  "Wemmel",
  "Vilvoorde",
  "Saint-Gilles",
  "Ixelles",
  "Anderlecht",
  "Auderghem",
  "Berchem-Sainte-Agathe",
  "Ville de Bruxelles",
  "Etterbeek",
  "Evere",
  "Forest",
  "Ganshoren",
  "Saint-Josse-ten-Noode",
  "Schaerbeek",
  "Watermael-Boitsfort",
  "Woluwe-Saint-Lambert",
  "Woluwe-Saint-Pierre"
];

export const sectors = [
  { value: 'Alimentation', label: 'Alimentation' },
  { value: 'Vêtements', label: 'Vêtements' },
  { value: 'Santé et beauté', label: 'Santé et beauté' },
  { value: 'Loisirs et divertissement', label: 'Loisirs et divertissement' },
  { value: 'Maison et jardin', label: 'Maison et jardin' },
  { value: 'Électronique et technologie', label: 'Électronique et technologie' },
  { value: 'Automobile', label: 'Automobile' },
  { value: 'Services financiers', label: 'Services financiers' },
  { value: 'Voyages et tourisme', label: 'Voyages et tourisme' },
  { value: 'Services professionnels', label: 'Services professionnels' },
  { value: 'Éducation et formation', label: 'Éducation et formation' },
  { value: 'Sport et fitness', label: 'Sport et fitness' },
  { value: 'Artisanat et artisanat d\'art', label: 'Artisanat et artisanat d\'art' },
  { value: 'Animaux de compagnie et fournitures pour animaux', label: 'Animaux de compagnie et fournitures pour animaux' },
  { value: 'Articles de cadeaux et souvenirs', label: 'Articles de cadeaux et souvenirs' },
  { value: 'Articles de papeterie et fournitures de bureau', label: 'Articles de papeterie et fournitures de bureau' },
  { value: 'Équipement de plein air et de camping', label: 'Équipement de plein air et de camping' },
  { value: 'Santé et bien-être', label: 'Santé et bien-être' },
  { value: 'Bricolage et rénovation résidentielle', label: 'Bricolage et rénovation résidentielle' },
  { value: 'Librairies et fournitures de bureau', label: 'Librairies et fournitures de bureau' },
  { value: 'Magasins de produits locaux et de spécialités', label: 'Magasins de produits locaux et de spécialités' },
  { value: 'Services de restauration et de traiteur', label: 'Services de restauration et de traiteur' },
  { value: 'Services de nettoyage et de blanchisserie', label: 'Services de nettoyage et de blanchisserie' },
  { value: 'Services de transport et de logistique', label: 'Services de transport et de logistique' },
  { value: 'Événements et divertissements en direct', label: 'Événements et divertissements en direct' }
];
  
export const categories = [
  { value: 'Fruits et légumes', label: 'Fruits et légumes' },
  { value: 'Produits Laitiers', label: 'Produits Laitiers' },
  { value: 'Viandes et Volailles', label: 'Viandes et Volailles' },
  { value: 'Poissons et Fruits de Mer', label: 'Poissons et Fruits de Mer' },
  { value: 'Céréales et Légumineuses', label: 'Céréales et Légumineuses' },
  { value: 'Boissons', label: 'Boissons' },
  { value: 'Produits de Soins Personnels', label: 'Produits de Soins Personnels' },
  { value: 'Vêtements', label: 'Vêtements' },
  { value: 'Autres', label: 'Autres' },
];